config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get :location, to: "pages#location"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boats do
    resources :bookings
  end
  get :my_bookings, to: "bookings#index"
  namespace :owner do
    resources :boats, only: [ :index, :show, :create, :edit, :update, :destroy ]
    resources :bookings do
      member do
        patch :cancel
        patch :accept
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :name, :price, :location, :description, :category, :capacity, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  CATEGORIES = ["motor boat", "sailing ship"]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat
  validates :start_at, :end_at, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boats
  has_one_attached :photo

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    @boats = Boat.all
    @boats = @boats.where('location ILIKE ?', params[:location]) if params[:location].present?

    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { boat: boat }),
        image_url: helpers.asset_url("antho.png")
      }
    end
  end

  def show
    @boat = Boat.find(params[:id])
    @booking = Booking.new
    @markers = [{
        lat: @boat.latitude,
        lng: @boat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { boat: @boat }),
        image_url: helpers.asset_url("antho.png")
      }]
  end

  def new
    @boat = Boat.new
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @tenant_bookings = Booking.where(user: current_user)
    @my_boats = Boat.where(user: current_user)
    @owner_bookings = Booking.where(boat: @my_boats)
  end

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @boat = Boat.find(params[:boat_id])
    @booking = Booking.new(booking_params)
    @booking.boat = @boat
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to my_bookings_path
    else
      render 'boats/show'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update(booking_params)
      redirect_to @booking
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to my_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_at, :end_at)
  end
end

app/controllers/owner/boats_controller.rb
class Owner::BoatsController < ApplicationController
  def index
    @boats = Boat.where(user: current_user)
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    if @boat.save
      redirect_to boat_path(@boat)
    else
      render :new
    end
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update
    @boat = Boat.find(params[:id])

    if @boat.update(boat_params)
      redirect_to @boat
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy
    redirect_to owner_boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :location, :price, :category, :capacity, :description , :photo)
  end
end

app/controllers/owner/bookings_controller.rb
module Owner
  class BookingsController < ApplicationController


    def index
      @owner_boats = Boat.all.where(user: current_user)
      @owner_bookings_canceled = []
      @owner_bookings_accepted = []
      @owner_bookings_pending = []
      @owner_boats.each do |boat|
        boat.bookings.each do |boat_booking|
          @owner_bookings_canceled << boat_booking if boat_booking.status == "Canceled"
          @owner_bookings_accepted << boat_booking if boat_booking.status == "Accepted"
          @owner_bookings_pending << boat_booking if boat_booking.status == "Pending"
        end
      end
    end

    def accept
      @booking = Booking.find(params[:id])
      @booking.status = "Accepted"
      @booking.save

      redirect_to my_bookings_path
    end

    def cancel
      @booking = Booking.find(params[:id])
      @booking.status = "Canceled"
      @booking.save

      redirect_to my_bookings_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
    @boats = Boat.all
    @locations = @boats.map(&:location).uniq

    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { boat: boat }),
        image_url: helpers.asset_url("antho.png")
      }
    end
  end

  def location
    @boats = Boat.where(boat.location = params[:location])
    # @boats = Boat.near
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/index.html.erb
<div class="container p-5">
  <div class="row text-center">
    <div class="col">
      <h1>Boats available at <strong><%= params[:location] %></strong></h1>
    </div>
  </div>
</div>
<div class="container p-5">
  <div class="row">
    <div class="col">
      <div style="width: 100%; height: 400px;margin:0 auto"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
<div class="container p-5">
  <div class="row">
      <% @boats.each do |boat| %>
      <div class="col-12 col-md-4">
        <div class="card-boat-homepage">
          <a href="<%= boat_path(boat) %>" class="link-dark text-decoration-none">
            <div class="card-trip my-2">
                <%= cl_image_tag boat.photo.key, height: 500, width: 400, crop: :fill  %>
                <div class="card-trip-infos">
                  <div>
                    <p class= "text-truncate"> 🧍‍♂️ <%= boat.capacity %> persons </p>
                    <p class= "text-truncate"> ⛵ Category : <%= boat.category %>  </p>
                    <h2> <%= boat.name %> </h2>
                    <p class= "text-truncate"> <%= boat.description %> </p>
                  </div>
                  <h2 class="card-trip-pricing"> <%= boat.price %>  <strong>€</strong> </h2>
                  <%=  cl_image_tag boat.user.photo.key, class:'card-trip-user avatar-bordered'%>
                </div>
            </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/boats/new.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col">
      <h1>Add a new boat :</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= simple_form_for([:owner, @boat]) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :category, collection: Boat::CATEGORIES, as: :radio_buttons%>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/boats/show.html.erb
<div class="container main-container py-5">
  <div class="row details">
    <div class="col-sm-12 col">
      <div class="card-boat-show">
        <div class="card-trip p-5 bg-gray">
          <%= cl_image_tag @boat.photo.key %>
          <div class="card-trip-infos my-5">
            <div>
              <p>⚓ Location : <strong><%= @boat.location %></strong></p>
              <p>⛵ Category :  <strong><%= @boat.category %></strong></p>
              <h1> <%= @boat.name %></h1>
              <p>🧍‍♂️ <%= @boat.capacity %> persons </p>
              <p>🧑‍✈️ Offered by <%= @boat.user.full_name  %>  </p>
            </div>
            <h2 class="card-trip-pricing"><%= @boat.price%> €</h2>
            <%=  cl_image_tag @boat.user.photo.key, class:'card-trip-user avatar-bordered'%>
          </div>
          <p class="my-2"> <%= @boat.description %> </p>
          <div>
            <h2 class="my-2">Booking conditions:</h2>
            <p>This boat can be chartered any day of the week for one day or more.</p>
            <h2 class="my-2">Cancellation policy:</h2>
            <p>Cancellation conditions Moderate.</p>
            <p>Moderate: 70% refund up to 10 days before arrival, excluding service fees and commission.</p>
            <h2 class="my-3">Book this boat :</h2>
            <%= simple_form_for [@boat, @booking] do |f| %>
              <%= f.input :start_at, html5: true %>
              <%= f.input :end_at, html5: true %>
              <%= f.button :submit, "Book Now", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="map"style="width: 40%; height: 600px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" class="">
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container p-3">
  <div class="row p-5">
    <div class="col">
      <h1 class="py-5">My bookings</h1>
      <% @tenant_bookings.each do |booking| %>
        <div class="card-product">
          <%= cl_image_tag booking.boat.photo.key, height: 500, width: 400, crop: :fill  %>
          <div class="card-product-infos p-5">
            <h2>You have booked <strong><%= booking.boat.name %></strong></h2>
            <p> from <strong><%= booking.start_at %></strong> to <strong><%= booking.end_at %></strong>.</p>
            <p>Total price <strong><%= ((booking.end_at - booking.start_at) * booking.boat.price ).to_i%></strong> € </p>
            <p>Your boat <strong><%= booking.boat.name%></strong>  will be ready on <%= booking.start_at %> at <%= booking.boat.location %> </p>
            <p>Booking status <strong><%= booking.status %></strong> </p>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>

<div class="container p-5">
  <div class="row">
    <div class="col">
    <h1 class="py-5">Dashboard</h1>
      <% @owner_bookings.each do |booking| %>
        <div class="card-product">
          <%= cl_image_tag booking.boat.photo.key, height: 500, width: 400, crop: :fill  %>
          <div class="card-product-infos p-">
            <h2><strong><%= booking.boat.name %></strong></h2>
            <p> from <strong><%= booking.start_at %></strong> to <strong><%= booking.end_at %></strong>.</p>
            <p>Total price <strong><%= ((booking.end_at - booking.start_at) * booking.boat.price ).to_i%></strong> € </p>
            <p>Your boat <strong><%= booking.boat.name%></strong> has been booked by <strong><%= booking.user.full_name %></strong> from <strong><%= booking.start_at %></strong> to <strong><%= booking.end_at %></strong>.</p>
            <p>Booking status <strong><%= booking.status %></strong> </p>
          </div>
        </div>
        <div class="p-2 ">
          <%= link_to 'Accept',  accept_owner_booking_path(booking), class:'btn btn-outline-success',  method: :patch, data:{ confirm: "Are you sure you want to accept this booking?"} %>
          <%= link_to 'Decline',  cancel_owner_booking_path(booking), class:'btn btn-outline-danger', method: :patch, data:{ confirm: "Are you sure you want to cancel this booking?"} %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Book a boat</h1>

<%= simple_form_for @booking do |f| %>
  <%= f.input :start_at, as: :datetime_picker %>
  <%= f.input :end_at, as: :datetime_picker %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boatnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/owner/boats/create.html.erb
<h1>Boats#create</h1>
<%= simple_form_for([:owner, @boat]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :location %>
  <%= f.input :category, collection: Boat::CATEGORIES, as: :radio_buttons%>
  <%= f.input :capacity %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/owner/boats/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit your Boat</h1>
    <div class="col">
      <%= simple_form_for([:owner, @boat]) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :category, collection: Boat::CATEGORIES, as: :radio_buttons%>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/owner/boats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>My boats</h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @boats.each do |boat| %>
      <div class="col-12 col-md-4">
        <div class="card-boat-homepage">
          <div class="card-trip my-2">
              <%= cl_image_tag boat.photo.key, height: 500, width: 400, crop: :fill  %>
              <div class="card-trip-infos">
                <div>
                  <p class= "text-truncate"> 🧍‍♂️ <%= boat.capacity %> persons </p>
                  <p class= "text-truncate"> ⛵ Category : <%= boat.category %>  </p>
                  <h2> <%= boat.name %> </h2>
                  <p class= "text-truncate"> <%= boat.description %> </p>
                </div>
                <h2 class="card-trip-pricing"> <%= boat.price %>  <strong>€</strong> </h2>
                <%=  cl_image_tag boat.user.photo.key, class:'card-trip-user avatar-bordered'%>
              </div>
              <div>
              <%= link_to 'Create a new boat', new_boat_path, class:'m-1 btn btn-primary'%>
              <%= link_to 'Edit boat',  edit_owner_boat_path(boat), class:'m-1 btn btn-success'%>
              </div>
              <div>
                <%= link_to_if !boat.bookings.any?, 'Delete boat',  owner_boat_path(boat) , class:'m-2 btn btn-danger',  method: :delete, data:{ confirm: "Are you sure you want to delete this boat?"} %>
              </div>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_info_window.html.erb
<h4><%= boat.name %></h4>
<p><%= boat.location %></p>
<p><%= boat.price %> €</p>

app/views/pages/location.html.erb
<h1>loc</h1>

<% @boats.each do |boat| %>
  <%= boat.name %> - <%= boat.location %>

<% end %>

app/views/shared/_banner.html.erb
<%# banner %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.picsum.photos/id/1083/5472/3648.jpg?hmac=CtOxgXc6Oe3TQvKBXtPsKVT9Z2Yg7SJKWVlgWPeMBUs);">
  <div class="container">
    <h1>BoatNb - <strong>Share and discover the boating lifestyle</strong>!</h1>
    <p>Discover boats perfect for any trip</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-dark ">
  <div class="container">
    <div class="row">
      <div class="col-md-4 pr-md-5">
        <a href="/" class="footer-site-logo d-block mb-4"><h2>BoatNb</h2></a>
        <%= image_tag "sailor-icon-11-915042515.png" , height: 100  %>
        <p>Share and discover the boating lifestyle</p>
      </div>
      <div class="col-md">
        <ul class="list-unstyled nav-links">
          <li><a href="#">Home</a></li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">My bookings</a></li>
          <li><a href="#">My boats</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
      <div class="col-md">
        <ul class="list-unstyled nav-links">
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms &amp; Conditions</a></li>
          <li><a href="#">Partners</a></li>
        </ul>
      </div>
      <div class="col-md text-md-center">
        <ul class="social list-unstyled">
          <li><a href="#"><i class="fab fa-facebook"></i></a></li>
          <li><a href="#"><i class="fab fa-twitter"></i></a></li>
          <li><a href="#"><i class="fab fa-instagram-square"></i></a></li>
          <li><a href="#"><i class="fab fa-pinterest"></i></a></li>
          <li><a href="#"><i class="fas fa-basketball-ball"></i></a></li>
        </ul>
        <p class="/"><a href="#" class="btn btn-tertiary">Contact Us</a></p>
      </div>
    </div>
    <hr>
    <div class="row ">
      <div class="col-12 text-center">
        <div class="copyright mt-5 pt-5">
        <p>Made with ❤️ by Lucas Vittaz, Sarah Menu, Anthony Gouvrillon</p>
        <p><small>© 2022 BoatNb All Rights Reserved.</small></p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= image_tag "sailor-icon-11-915042515.png" , height: 50  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "My bookings", my_bookings_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "My boats", owner_boats_path, class:'nav-link' %>
        </li>
      </ul>
      <%= form_tag boats_path, method: :get, class: 'd-flex' do %>
        <%= text_field_tag :location,
            params[:location],
            class: "form-control",
            placeholder: "Place of departure"%>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
        <% if !current_user %>
          <%= link_to "Log in", user_session_path, class:'nav-link' %>
        <% else %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:'nav-link' %>
        <% end %>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class:'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>